version: "3.9"
services:
    postgres:
        container_name: gregdemo_postgres_container
        image: postgres:latest
        working_dir: /app
        restart: always
        ports:
            - "12367:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - "postgres_gregdemo_12367:/var/lib/postgresql"

volumes:
    postgres_gregdemo_12367:
